[package]
name = "record_mouse_and_keypresses"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "record_mouse_and_keypresses"
path = "src/main.rs"

[dependencies]
rdev = "0.5.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
x11 = "2.18.2"  # for X11 key translation
